module.exports = Object.freeze({
    Url: {
        CREATE_CLIENT: (base) => `${base}/clients`,
        SEARCH_CLIENT: (base, id) => `${base}/clients/${encodeURIComponent(id)}?detailsLevel=FULL`,
        SEARCH_GROUPS: (base) => `${base}/groups:search?detailsLevel=FULL`,
        CREATE_GROUP: (base) => `${base}/groups`,
    },
    Msg: {
        INVALID_QUERY: 'La información no fue enviada de forma correcta',
        INVALID_REQUEST: 'Invalid Request',
        INVALID_CREDITO: 'ya se encuentra en estado: PENDING_APPROVAL o no existe el credito',
        NO_TENANT_IN_PROPERTIES: 'No se encontro configuracion de tenant',
        NO_TENANT_IN_BODY: 'No se encontro TenantId en la peticion',
        NO_CURP: 'No se encontro CURP en el body de la peticion',
        NO_CLIENT_SEARCH_TERM: 'No se encontro curp/rfc en el body de la peticion',
        NO_ENCODED_KEY: 'No se encontro encodedKey',
        NO_NAME: 'No se encontro name',
        NO_GROUP_NAME: 'No se encontro groupName',
        NO_BRANCH_KEY: 'No se encontro branchKey',
        SUCCESS_X_RFC: 'Consulta realizada con exito',
        SUCCESS_X_ID: 'Consulta Adicional por nombre exitosa',
        NO_RESULTADOS: '<Text>0,No se encontaron resultados</Text>',
        NO_SERVICE: 'No fue posible consultar el servicio intenta nuevamente',
        GUARDAR_PARCIAL: 'Guarda parcialmente y regresa a la pantalla principal para el envío de información a PLD.',
        UNIFICADO_FORM: 'Información procesada correctamente.',
        MSG_ESTADOCUENTA: 'Error al tratar de consultar el saldo, verifica tu id de credito',
    },
    Actions: {
        APPROVE: 'APPROVE',
        UTC6: 'T00:00:00-06:00',
        UTC5: 'T00:00:00-05:00',
        ALERT_MESSAGE: 'AlertMessage',
        CLIENTE_ERROR: 'ClientError',
        ERROR_MOBILE_FALSE: 'false',
        EJECUCION_CONSULTA_MOBILE_NO: 'No',
        EJECUCION_CONSULTA_MOBILE_SI: 'Si',
        TIME_ENGINE: 20000,
    },
    Notes: {
        NOTES_APPROVE: 'Aprobar cuenta',
        NOTES_MATURITY: 'INICIO PLAZO',
        TIPO_GRUPAL: 'grupal',
        ESTATUS_GRUPAL_FORMACION: 'En Formación',
    },
    Http: {
        Verbs: {
            POST: 'POST',
            GET: 'GET',
        },
    },
    Param: {
        Moral: 'GROUP',
        Fisica: 'CLIENT',
        TIPO_DESEMBOLSO_DIE: 'DIE BANCO',
    },
    CodeErrors: {
        CEROS: '00000',
        ADICIONAL_ID: '00048',
    },
});
